services:

  y:
    build: .
    # we let the assistant container up indefinitely
    command: tail -f /dev/null
    develop:
        watch:
          - action: sync
            path: ./src
            target: /workspace
          - action: rebuild
            path: requirements.txt
    volumes:
      #! you can mount any input/output folders of your chosing here
      # - ./some/path:/workspace/in
      - ./out:/workspace/out
